// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
import '../styles/globals.css';

//internal imports
import { kulkonect_chatProvider } from '../Context/kulkonect_chatContext';
import { NavBar } from '../Components/index';

const MyApp = ({ Component, pageProps }) => (
    <div>
        <kulkonect_chatProvider>
            <NavBar />

            <Component {...pageProps} />
        </kulkonect_chatProvider>
        
    </div>
);

export default MyApp;